services:
  - type: web
    name: uniflow-web-backend
    env: node
    rootDir: programa/backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/salud
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
